apiVersion: apps/v1
kind: Deployment
metadata:
  name: last_batch_bookalbum
  labels:
    app: last_batch_bookalbum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: last_batch_bookalbum
  template:
    metadata:
      labels:
        app: last_batch_bookalbum
    spec:
      containers:
      - name: last_batch_bookalbum
        image: niri1234/lastbatch_php:latest
        ports:
        - containerPort: 80
