apiVersion: v1
kind: Service
metadata:
  labels:
    app: last_batch_bookalbum
  name: last_batch_bookalbum
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: last_batch_bookalbum

