apiVersion: apps/v1
kind: Deployment
metadata:
  name: lastbatchbookalbum1
  labels:
    app: lastbatchbookalbum1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lastbatchbookalbum1
  template:
    metadata:
      labels:
        app: lastbatchbookalbum1
    spec:
      containers:
      - name: lastbatchbookalbum1
        image: niri1234/lastbatch_php:latest
        ports:
        - containerPort: 80
