apiVersion: v1
kind: Service
metadata:
  labels:
    app: lastbatchbookalbum11
  name: lastbatchbookalbum11
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: lastbatchbookalbum11

