apiVersion: apps/v1
kind: Deployment
metadata:
  name: lastbatchbookalbum
  labels:
    app: lastbatchbookalbum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lastbatchbookalbum
  template:
    metadata:
      labels:
        app: lastbatchbookalbum
    spec:
      containers:
      - name: lastbatchbookalbum
        image: niri1234/lastbatch_php:latest
        ports:
        - containerPort: 80
